---
- name: clone roles
  hosts: all
  become: true
  vars:
    git_repository: https://github.com/shtaen/Ansible_roles
    git_branch: main
  tasks:
    - name: /etc/ansible/roles
      file:
       path: /etc/ansible/roles
       state: directory
       mode: '0755'
    - name: checkout
      git:
       repo: "{{ git_repository }}"
       dest: /etc/ansible/roles
       version: "{{ git_branch }}"
     